apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nuevita-authh
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:progressDeadlineSeconds": {}
          "f:replicas": {}
          "f:revisionHistoryLimit": {}
          "f:selector": {}
          "f:strategy":
            "f:rollingUpdate":
              .: {}
              "f:maxSurge": {}
              "f:maxUnavailable": {}
            "f:type": {}
          "f:template":
            "f:metadata":
              "f:labels":
                .: {}
                "f:app": {}
            "f:spec":
              "f:containers":
                'k:{"name":"borr-1"}':
                  .: {}
                  "f:env":
                    .: {}
                    'k:{"name":"BD_NAME"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"PASSWORD"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"PORT"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"SECRET_JWT"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"SERVER"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"SERVER_PORT"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                    'k:{"name":"USER"}':
                      .: {}
                      "f:name": {}
                      "f:valueFrom":
                        .: {}
                        "f:configMapKeyRef": {}
                  "f:image": {}
                  "f:imagePullPolicy": {}
                  "f:name": {}
                  "f:resources": {}
                  "f:terminationMessagePath": {}
                  "f:terminationMessagePolicy": {}
              "f:dnsPolicy": {}
              "f:restartPolicy": {}
              "f:schedulerName": {}
              "f:securityContext": {}
              "f:terminationGracePeriodSeconds": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-24T04:11:24Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:annotations":
            .: {}
            "f:deployment.kubernetes.io/revision": {}
        "f:status":
          "f:availableReplicas": {}
          "f:conditions":
            .: {}
            'k:{"type":"Available"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"Progressing"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:lastUpdateTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:observedGeneration": {}
          "f:readyReplicas": {}
          "f:replicas": {}
          "f:updatedReplicas": {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-12-24T04:11:55Z"
  name: nuevita-authh
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nuevita-authh
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nuevita-authh
    spec:
      containers:
        - env:
            - name: BD_NAME
              valueFrom:
                configMapKeyRef:
                  key: BD_NAME
                  name: nuevita-authh-config-v2ma
            - name: SERVER
              valueFrom:
                configMapKeyRef:
                  key: SERVER
                  name: nuevita-authh-config-v2ma
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: nuevita-authh-config-v2ma
            - name: USER
              valueFrom:
                configMapKeyRef:
                  key: USER
                  name: nuevita-authh-config-v2ma
            - name: PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PASSWORD
                  name: nuevita-authh-config-v2ma
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PORT
                  name: nuevita-authh-config-v2ma
            - name: SECRET_JWT
              valueFrom:
                configMapKeyRef:
                  key: SECRET_JWT
                  name: nuevita-authh-config-v2ma
          image: gcr.io/encoded-aspect-371604/github.com/huamanangel/borr
          imagePullPolicy: IfNotPresent
          name: borr-1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: nuevita-authh
  managedFields:
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:maxReplicas": {}
          "f:metrics": {}
          "f:minReplicas": {}
          "f:scaleTargetRef":
            "f:apiVersion": {}
            "f:kind": {}
            "f:name": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-24T04:11:24Z"
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      fieldsV1:
        "f:status":
          "f:conditions":
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"ScalingActive"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              "f:lastTransitionTime": {}
              "f:message": {}
              "f:reason": {}
              "f:status": {}
              "f:type": {}
          "f:currentMetrics": {}
          "f:currentReplicas": {}
          "f:desiredReplicas": {}
      manager: vpa-recommender
      operation: Update
      subresource: status
      time: "2022-12-24T04:11:41Z"
  name: nuevita-authh-hpa-yncr
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nuevita-authh
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: nuevita-authh
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:labels":
            .: {}
            "f:app": {}
        "f:spec":
          "f:allocateLoadBalancerNodePorts": {}
          "f:externalTrafficPolicy": {}
          "f:internalTrafficPolicy": {}
          "f:ports":
            .: {}
            'k:{"port":80,"protocol":"TCP"}':
              .: {}
              "f:port": {}
              "f:protocol": {}
              "f:targetPort": {}
          "f:selector": {}
          "f:sessionAffinity": {}
          "f:type": {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2022-12-24T04:21:26Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        "f:metadata":
          "f:finalizers":
            .: {}
            'v:"service.kubernetes.io/load-balancer-cleanup"': {}
        "f:status":
          "f:loadBalancer":
            "f:ingress": {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: "2022-12-24T04:22:14Z"
  name: nuevita-authh-service
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.28.22.147
  clusterIPs:
    - 10.28.22.147
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30765
      port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app: nuevita-authh
  sessionAffinity: None
  type: LoadBalancer
